
obj-m += dram.o 

all:
	make -C /lib/modules/$(shell uname -r)/build M=/home/murt/my_github/teonho/a/ma_nguon/dram modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=/home/murt/my_github/teonho/a/ma_nguon/dram clean

