
obj-m += mm.o 

all:
	make -C /lib/modules/$(shell uname -r)/build M=/home/murt/my_github/teonho/a/ma_nguon/mm-struct modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=/home/murt/my_github/teonho/a/ma_nguon/mm-struct clean

